package scanexec

import (
	"crypto/sha1"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"github.com/qiwentaidi/trailblazer/pkg/config"
	"github.com/qiwentaidi/trailblazer/pkg/core/crawl"
	"github.com/qiwentaidi/trailblazer/pkg/core/database"
	"github.com/qiwentaidi/trailblazer/pkg/core/structs"
	"github.com/qiwentaidi/trailblazer/pkg/core/vuln"
	weaklogin "github.com/qiwentaidi/trailblazer/pkg/core/vuln/weaklogin"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/qiwentaidi/clients"
	arrayutil "github.com/qiwentaidi/utils/array"
)

type Options struct {
	TaskID         string
	Version        int
	BlackDomain    []string
	HighRiskRouter []string
	Authentication []string
	Placeholder    map[string]string
	WeakCreds      []string
	OpenAI         config.OpenAI
	VulnDetection  config.VulnDetection
	DataStore      database.ScanDataStore
}

type SensitiveItem struct {
	Value      string
	Source     string
	AIVerified bool
}

type AssetInfo struct {
	Email          []SensitiveItem
	IDCard         []SensitiveItem
	Phone          []SensitiveItem
	IPURL          []SensitiveItem
	Sensitive      []SensitiveItem
	FrontendRoutes []string
	APIRoutes      []string
	APIRoots       []string
}

type TargetResult struct {
	Target           string
	TreeData         []crawl.ElTreeNode
	NetworkURLs      []string
	APIRecords       []crawl.NetworkRecord
	ProtocolTraces   []crawl.ProtocolTraceRecord
	JSResources      []database.JSResource
	StaticHintBundle crawl.StaticEndpointHintBundle
	Assets           AssetInfo
	Fingerprints     []structs.FingerprintResult
	Vulnerabilities  []database.VulnRecord
}

type vulnSliceCollector struct {
	items []database.VulnRecord
}

func (c *vulnSliceCollector) Collect(vuln database.VulnRecord) {
	c.items = append(c.items, vuln)
}

type compositeScanDataStore struct {
	stores []database.ScanDataStore
}

const denyTemplateMinClusterSize = 3

type denyTemplateAIReviewer interface {
	JudgeDenyTemplate(requestPreview, responsePreview string) (bool, string, error)
}

const manualUnauthorizedReviewConfidenceCap = 59

type unauthorizedAIReviewer interface {
	ReviewUnauthorizedAccess(targetURL, requestPreview, responsePreview string) (crawl.UnauthorizedAIReview, error)
}

func asDenyTemplateReviewer(checker *crawl.SensitiveInfoChecker) denyTemplateAIReviewer {
	if checker == nil {
		return nil
	}
	return checker
}

type denyTemplateAIReviewResult struct {
	confirmed bool
}

type denyTemplateCluster struct {
	id          string
	kind        string
	label       string
	fingerprint string
	items       []*database.VulnRecord
}

var denyTemplateAIReviewCache sync.Map

var volatileResponseKeys = map[string]struct{}{
	"error_hint":   {},
	"hint":         {},
	"trace_id":     {},
	"traceid":      {},
	"request_id":   {},
	"requestid":    {},
	"req_id":       {},
	"reqid":        {},
	"timestamp":    {},
	"time":         {},
	"ts":           {},
	"nonce":        {},
	"sign":         {},
	"signature":    {},
	"rand":         {},
	"random":       {},
	"token":        {},
	"access_token": {},
}

var builtinWeakCreds = []string{
	"admin:admin",
	"root:root",
	"admin:123456",
}

const autogeneratedLoginEventCred = "1:Test@123456"

func (s compositeScanDataStore) ListJSResources(taskID string, versions ...int) ([]database.JSResource, error) {
	var combined []database.JSResource
	for _, store := range s.stores {
		if store == nil {
			continue
		}
		items, err := store.ListJSResources(taskID, versions...)
		if err != nil {
			return nil, err
		}
		combined = append(combined, items...)
	}
	return combined, nil
}

func (s compositeScanDataStore) ListAPIResources(taskID string, versions ...int) ([]database.APIResource, error) {
	var combined []database.APIResource
	for _, store := range s.stores {
		if store == nil {
			continue
		}
		items, err := store.ListAPIResources(taskID, versions...)
		if err != nil {
			return nil, err
		}
		combined = append(combined, items...)
	}
	return combined, nil
}

func (s compositeScanDataStore) ListProtocolTraces(taskID string, versions ...int) ([]database.ProtocolTraceRecord, error) {
	var combined []database.ProtocolTraceRecord
	for _, store := range s.stores {
		if store == nil {
			continue
		}
		items, err := store.ListProtocolTraces(taskID, versions...)
		if err != nil {
			return nil, err
		}
		combined = append(combined, items...)
	}
	return combined, nil
}

func RunTarget(targetURL string, options Options) (*TargetResult, error) {
	if _, err := clients.SimpleGet(targetURL, clients.DefaultRestyClient()); err != nil {
		return nil, err
	}

	result := &TargetResult{
		Target:          targetURL,
		Assets:          AssetInfo{},
		Fingerprints:    []structs.FingerprintResult{},
		Vulnerabilities: []database.VulnRecord{},
	}

	e := crawl.Extract{}
	filter := crawl.Filter{}

	allNetworkURLs, capturedAPIRecords, capturedProtocolTraces, capturedFrontendRoutes := crawl.CaptureNetworkActivity(targetURL)
	for i := range capturedProtocolTraces {
		if strings.TrimSpace(capturedProtocolTraces[i].TaskID) == "" {
			capturedProtocolTraces[i].TaskID = options.TaskID
		}
	}
	mergedAPIRecords := mergeCapturedAPIRecordsWithProtocolTraces(capturedAPIRecords, capturedProtocolTraces)

	result.NetworkURLs = allNetworkURLs
	result.TreeData = crawl.BuildElTree(allNetworkURLs)
	result.APIRecords = mergedAPIRecords
	result.ProtocolTraces = capturedProtocolTraces

	classified := e.ClassifyLinks(allNetworkURLs, options.BlackDomain)

	allJS := mergeJSLinks(targetURL, classified, options.BlackDomain)
	result.JSResources = fetchStaticHintJSResources(options.TaskID, options.Version, targetURL, allJS, options.BlackDomain)
	result.StaticHintBundle = crawl.BuildStaticEndpointHintBundle(result.JSResources)

	var aiChecker *crawl.SensitiveInfoChecker
	if options.OpenAI.Enabled && strings.TrimSpace(options.OpenAI.APIKey) != "" {
		aiChecker = crawl.NewSensitiveInfoChecker(
			options.OpenAI.APIKey,
			options.OpenAI.BaseURL,
			options.OpenAI.Model,
		)
	}

	findSomething := crawl.Scan(targetURL, allJS, aiChecker)
	result.Assets = buildAssetInfo(findSomething)
	result.Assets.FrontendRoutes = buildFrontendRoutes(capturedFrontendRoutes)

	staticAPIRoutes := buildStaticAPIRoutes(findSomething, classified, filter)
	apiRouter := buildAPIRoutes(findSomething, classified, mergedAPIRecords, capturedProtocolTraces, filter)
	result.Assets.APIRoutes = apiRouter
	result.Assets.APIRoots = buildAPIRoots(targetURL, apiRouter, classified, filter)
	logJSHookCaptureDelta(targetURL, result.Assets.FrontendRoutes, capturedFrontendRoutes, staticAPIRoutes, apiRouter, mergedAPIRecords, capturedProtocolTraces)

	workingStore := buildWorkingDataStore(options, targetURL, result.JSResources, mergedAPIRecords, capturedProtocolTraces)
	collector := &vulnSliceCollector{}
	for _, root := range result.Assets.APIRoots {
		crawl.AnalyzeAPIWithCollector(buildJSFindOptions(options, targetURL, apiRouter, root, result.StaticHintBundle, aiChecker, workingStore), collector)
	}
	result.Vulnerabilities = dedupeVulnerabilities(collector.items)
	bindStaticContexts(result.Vulnerabilities, result.JSResources)
	filteredUnauthorizedTemplates := make(map[string]struct{})
	aiReviewer := asDenyTemplateReviewer(aiChecker)
	result.Vulnerabilities = annotateUnauthorizedNoise(result.Vulnerabilities, aiReviewer, filteredUnauthorizedTemplates)
	result.Fingerprints = vuln.ScanDiscoveredRequests(
		targetURL,
		buildDiscoveredRequests(mergedAPIRecords),
		options.VulnDetection.Enabled,
	)
	result.Vulnerabilities = append(result.Vulnerabilities, runWeakLoginDetections(targetURL, options, mergedAPIRecords, capturedFrontendRoutes)...)
	result.Vulnerabilities = append(result.Vulnerabilities, buildAssetVulnerabilities(result.Assets)...)
	result.Vulnerabilities = dedupeVulnerabilities(result.Vulnerabilities)
	dedupeAssets(&result.Assets)

	return result, nil
}

func buildJSFindOptions(
	options Options,
	targetURL string,
	apiRouter []string,
	root string,
	hintBundle crawl.StaticEndpointHintBundle,
	aiChecker *crawl.SensitiveInfoChecker,
	dataStore database.ScanDataStore,
) structs.JSFindOptions {
	vulnDetection := resolveVulnDetection(options.VulnDetection)
	var aiCheckerValue interface{}
	if aiChecker != nil {
		aiCheckerValue = aiChecker
	}
	return structs.JSFindOptions{
		TaskID:                    options.TaskID,
		Version:                   options.Version,
		HomeURL:                   targetURL,
		ApiList:                   apiRouter,
		ApiRoot:                   root,
		StaticMethodHints:         hintBundle.Methods,
		StaticHeaderHints:         hintBundle.Headers,
		StaticConstantParams:      hintBundle.ConstantParams,
		StaticRequestPayloadHints: hintBundle.RequestPayload,
		SkipVulnScan:              !vulnDetection.Enabled,
		HighRiskRouter:            options.HighRiskRouter,
		Authentication:            options.Authentication,
		Placeholder:               options.Placeholder,
		LFIConfig:                 vulnDetection.LFI,
		SSRFConfig:                vulnDetection.SSRF,
		RedirectConfig:            vulnDetection.Redirect,
		SQLInjConfig:              vulnDetection.SQLInjection,
		XSSConfig:                 vulnDetection.XSS,
		UploadConfig:              vulnDetection.Upload,
		AIChecker:                 aiCheckerValue,
		DataStore:                 dataStore,
	}
}

func runWeakLoginDetections(
	targetURL string,
	options Options,
	apiRecords []crawl.NetworkRecord,
	frontendRoutes []crawl.FrontendRouteRecord,
) []database.VulnRecord {
	if !options.VulnDetection.Enabled {
		return nil
	}

	weakCreds := resolveWeakCreds(options.WeakCreds)
	if len(weakCreds) == 0 {
		return nil
	}

	targets := inferWeakLoginTargetURLs(targetURL, apiRecords, frontendRoutes)
	if len(targets) == 0 {
		return nil
	}

	vulns := make([]database.VulnRecord, 0, 1)
	for _, candidateURL := range targets {
		prefilledResult, err := weaklogin.TestPrefilledFormLogin(candidateURL)
		if err != nil {
			fmt.Printf("[警告] 预填充凭据登录探测失败: %s err=%v\n", candidateURL, err)
		} else if prefilledResult != nil && prefilledResult.Vulnerable && prefilledResult.UsedPrefilledCred {
			fmt.Printf("[信息] 登录页已存在预填充凭据并可直接登录: %s\n", candidateURL)
			break
		}

		result, err := weaklogin.TestWeakFormLogin(candidateURL, weakCreds)
		if err != nil {
			fmt.Printf("[警告] 弱口令检测执行失败: %s err=%v\n", candidateURL, err)
			continue
		}
		if result == nil || !result.Vulnerable {
			continue
		}

		fmt.Printf("[信息] 发现弱口令漏洞: %s（账号: %s）\n", candidateURL, result.Username)
		vulns = append(vulns, database.VulnRecord{
			TaskID:         options.TaskID,
			Version:        options.Version,
			VulnID:         uuid.New().String(),
			Title:          "弱口令登录",
			Level:          "high",
			Type:           "WEAK_PASSWORD",
			URL:            candidateURL,
			Method:         "FORM",
			Request:        buildWeakLoginRequestPreview(candidateURL, result.Username, result.Password),
			Response:       result.Response,
			ResponseLength: len(result.Response),
			Description:    fmt.Sprintf("发现弱口令登录漏洞，登录页: %s，用户名: %s，密码: %s，原因: %s", candidateURL, result.Username, result.Password, result.Reason),
			AIVerified:     false,
			CreatedAt:      time.Now(),
		})
		break
	}

	return vulns
}

func resolveWeakCreds(configured []string) []string {
	combined := make([]string, 0, len(configured)+len(builtinWeakCreds)+1)
	combined = append(combined, configured...)
	if len(configured) == 0 {
		combined = append(combined, builtinWeakCreds...)
	}
	combined = append(combined, autogeneratedLoginEventCred)

	seen := make(map[string]struct{}, len(combined))
	result := make([]string, 0, len(combined))
	for _, item := range combined {
		normalized := normalizeWeakCred(item)
		if normalized == "" {
			continue
		}
		if _, ok := seen[normalized]; ok {
			continue
		}
		seen[normalized] = struct{}{}
		result = append(result, normalized)
	}
	return result
}

func normalizeWeakCred(raw string) string {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return ""
	}
	parts := strings.SplitN(raw, ":", 2)
	if len(parts) != 2 {
		return ""
	}
	username := strings.TrimSpace(parts[0])
	password := strings.TrimSpace(parts[1])
	if username == "" || password == "" {
		return ""
	}
	return username + ":" + password
}

func inferWeakLoginTargetURLs(
	targetURL string,
	apiRecords []crawl.NetworkRecord,
	frontendRoutes []crawl.FrontendRouteRecord,
) []string {
	seen := map[string]struct{}{}
	result := make([]string, 0, 8)
	addCandidate := func(raw string) {
		candidate := normalizeWeakLoginTargetURL(targetURL, raw)
		if candidate == "" {
			return
		}
		if _, ok := seen[candidate]; ok {
			return
		}
		seen[candidate] = struct{}{}
		result = append(result, candidate)
	}

	if looksLikeLoginLocation(targetURL) {
		addCandidate(targetURL)
	}

	for _, record := range apiRecords {
		if looksLikeLoginLocation(record.PageURL) || looksLikeLoginRequest(record) {
			addCandidate(record.PageURL)
		}
	}

	for _, record := range frontendRoutes {
		if looksLikeLoginLocation(record.Path) || looksLikeLoginLocation(record.PageURL) {
			addCandidate(record.Path)
			addCandidate(record.PageURL)
		}
	}

	if len(result) == 0 {
		addCandidate(targetURL)
	}

	return result
}

func normalizeWeakLoginTargetURL(baseTargetURL, raw string) string {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return ""
	}

	parsedBase, err := url.Parse(strings.TrimSpace(baseTargetURL))
	if err != nil {
		return ""
	}

	parsed, err := url.Parse(raw)
	if err != nil {
		return ""
	}
	if parsed.Scheme != "" && parsed.Host != "" {
		return parsed.String()
	}

	if strings.HasPrefix(raw, "#") {
		clone := *parsedBase
		clone.Fragment = strings.TrimPrefix(raw, "#")
		return clone.String()
	}

	return parsedBase.ResolveReference(parsed).String()
}

func looksLikeLoginRequest(record crawl.NetworkRecord) bool {
	requestURL := strings.ToLower(strings.TrimSpace(record.URL))
	requestBody := strings.ToLower(strings.TrimSpace(record.RequestBody))
	pageURL := strings.ToLower(strings.TrimSpace(record.PageURL))

	if looksLikeLoginLocation(requestURL) || looksLikeLoginLocation(pageURL) {
		return true
	}

	if strings.Contains(requestBody, "username") && strings.Contains(requestBody, "password") {
		return true
	}
	if strings.Contains(requestBody, "account") && strings.Contains(requestBody, "password") {
		return true
	}
	return false
}

func looksLikeLoginLocation(raw string) bool {
	raw = strings.ToLower(strings.TrimSpace(raw))
	if raw == "" {
		return false
	}
	keywords := []string{
		"login",
		"signin",
		"sign-in",
		"auth/login",
		"/auth",
		"passport",
		"session",
		"登录",
		"登陆",
	}
	for _, keyword := range keywords {
		if strings.Contains(raw, keyword) {
			return true
		}
	}
	return false
}

func buildWeakLoginRequestPreview(targetURL, username, password string) string {
	return fmt.Sprintf("FORM %s\nusername=%s\npassword=%s", targetURL, username, password)
}

func resolveVulnDetection(options config.VulnDetection) config.VulnDetection {
	if options.Enabled {
		return options
	}

	options.SQLInjection.Enabled = false
	options.LFI.Enabled = false
	options.SSRF.Enabled = false
	options.Redirect.Enabled = false
	options.XSS.Enabled = false
	options.Upload.Enabled = false
	return options
}

func buildDiscoveredRequests(records []crawl.NetworkRecord) []structs.DiscoveredRequest {
	requests := make([]structs.DiscoveredRequest, 0, len(records))
	for _, record := range records {
		requestURL := strings.TrimSpace(record.URL)
		if requestURL == "" {
			continue
		}
		headers := make(map[string]string, len(record.RequestHeaders))
		contentType := ""
		for key, value := range record.RequestHeaders {
			headers[key] = value
			if strings.EqualFold(key, "Content-Type") {
				contentType = value
			}
		}
		requests = append(requests, structs.DiscoveredRequest{
			URL:              requestURL,
			Method:           record.Method,
			Headers:          headers,
			Body:             record.RequestBody,
			ContentType:      contentType,
			ResponseHeaders:  record.ResponseHeaders,
			ResponseBody:     record.ResponseBody,
			ResponseCode:     record.ResponseCode,
			ResponseMIMEType: record.MIMEType,
			Source:           "dynamic-browser-capture",
		})
	}
	return requests
}

func buildWorkingDataStore(
	options Options,
	targetURL string,
	jsResources []database.JSResource,
	apiRecords []crawl.NetworkRecord,
	protocolTraces []crawl.ProtocolTraceRecord,
) database.ScanDataStore {
	memoryStore := database.NewMemoryScanDataStore()
	memoryStore.AddJSResources(options.TaskID, jsResources)

	apiResources := make([]database.APIResource, 0, len(apiRecords))
	for _, record := range apiRecords {
		apiResources = append(apiResources, database.APIResource{
			TaskID:           options.TaskID,
			Version:          options.Version,
			URL:              record.URL,
			Method:           record.Method,
			TraceID:          record.TraceID,
			HasProtocolTrace: record.HasProtocolTrace,
			RequestHeaders:   record.RequestHeaders,
			RequestBody:      record.RequestBody,
			ResponseHeaders:  record.ResponseHeaders,
			ResponseBody:     record.ResponseBody,
			ResponseCode:     record.ResponseCode,
			Headers:          record.ResponseHeaders,
			FetchedAt:        record.FetchedAt,
		})
	}
	memoryStore.AddAPIResources(options.TaskID, apiResources)

	normalizedTraces := make([]database.ProtocolTraceRecord, 0, len(protocolTraces))
	for _, record := range protocolTraces {
		trace := normalizeProtocolTraceForView(record, options.Version, targetURL)
		normalizedTraces = append(normalizedTraces, trace)
	}
	memoryStore.AddProtocolTraces(options.TaskID, normalizedTraces)

	if options.DataStore == nil {
		return memoryStore
	}
	return compositeScanDataStore{stores: []database.ScanDataStore{memoryStore, options.DataStore}}
}

func normalizeProtocolTraceForView(record crawl.ProtocolTraceRecord, version int, targetURL string) database.ProtocolTraceRecord {
	requestSteps := make([]database.ProtocolCryptoStep, 0, len(record.RequestSteps))
	for _, step := range record.RequestSteps {
		requestSteps = append(requestSteps, database.ProtocolCryptoStep{
			Source:        step.Source,
			Algorithm:     step.Algorithm,
			InputPreview:  step.InputPreview,
			OutputPreview: step.OutputPreview,
			CallID:        step.CallID,
			ParentCallID:  step.ParentCallID,
			FunctionPath:  step.FunctionPath,
			ModuleID:      step.ModuleID,
			Stack:         step.Stack,
			CapturedAtMS:  step.CapturedAtMS,
		})
	}
	responseSteps := make([]database.ProtocolCryptoStep, 0, len(record.ResponseSteps))
	for _, step := range record.ResponseSteps {
		responseSteps = append(responseSteps, database.ProtocolCryptoStep{
			Source:        step.Source,
			Algorithm:     step.Algorithm,
			InputPreview:  step.InputPreview,
			OutputPreview: step.OutputPreview,
			CallID:        step.CallID,
			ParentCallID:  step.ParentCallID,
			FunctionPath:  step.FunctionPath,
			ModuleID:      step.ModuleID,
			Stack:         step.Stack,
			CapturedAtMS:  step.CapturedAtMS,
		})
	}
	dbTrace := database.ProtocolTraceRecord{
		TaskID:                 record.TaskID,
		Version:                version,
		TargetURL:              targetURL,
		TraceID:                record.TraceID,
		Transport:              record.Transport,
		PageURL:                record.PageURL,
		RequestURL:             record.RequestURL,
		Method:                 record.Method,
		RequestHeaders:         record.RequestHeaders,
		RequestBeforeTransform: record.RequestBeforeTransform,
		FinalRequestBody:       record.FinalRequestBody,
		RequestSteps:           requestSteps,
		ResponseSteps:          responseSteps,
		SignatureFields:        record.SignatureFields,
		DynamicParams:          record.DynamicParams,
		SessionMaterials:       record.SessionMaterials,
		Algorithms:             record.Algorithms,
		Stack:                  record.Stack,
		CreatedAt:              record.CreatedAt,
	}
	dbTrace.NormalizeForView()
	return dbTrace
}

func mergeJSLinks(targetURL string, classified crawl.NetworkLinks, blackDomain []string) []string {
	e := crawl.Extract{}
	filter := crawl.Filter{}

	staticJsLinks := filter.Blacklist(e.StaticJSLink(targetURL), blackDomain)
	classified.Classification.JS = filter.Blacklist(classified.Classification.JS, blackDomain)

	allJS := classified.Classification.JS
	if len(classified.Classification.JS) > 0 {
		for _, static := range staticJsLinks {
			present := false
			for _, dynamic := range classified.Classification.JS {
				if strings.Contains(dynamic, static) || strings.Contains(static, dynamic) {
					present = true
					break
				}
			}
			if !present {
				allJS = append(allJS, static)
			}
		}
	} else {
		allJS = append(allJS, staticJsLinks...)
	}

	return arrayutil.RemoveDuplicates(allJS)
}

func fetchStaticHintJSResources(taskID string, version int, homeURL string, jsLinks []string, blackDomain []string) []database.JSResource {
	const maxStaticHintJS = 40

	filter := crawl.Filter{}
	tempDir, err := os.MkdirTemp("", "trailblazer-shared-js-*")
	if err != nil {
		return nil
	}
	defer os.RemoveAll(tempDir)

	result := make([]database.JSResource, 0, maxStaticHintJS)
	for _, jsURL := range jsLinks {
		if len(result) >= maxStaticHintJS {
			break
		}
		resolvedURL := normalizeJSURL(homeURL, jsURL)
		if strings.TrimSpace(resolvedURL) == "" || filter.IsBlacklist(resolvedURL, blackDomain) {
			continue
		}

		resp, err := clients.SimpleGet(resolvedURL, clients.DefaultRestyClient())
		if err != nil {
			continue
		}

		filePath := filepath.Join(tempDir, buildTempJSFileName(resolvedURL))
		if err := os.WriteFile(filePath, resp.Body(), 0o600); err != nil {
			continue
		}
		fileContent, err := os.ReadFile(filePath)
		_ = os.Remove(filePath)
		if err != nil {
			continue
		}

		result = append(result, database.JSResource{
			TaskID:       taskID,
			Version:      version,
			URL:          resolvedURL,
			Content:      string(fileContent),
			ResponseCode: resp.StatusCode(),
			Size:         len(fileContent),
			FetchedAt:    time.Now(),
		})
	}

	return result
}

func normalizeJSURL(homeURL, jsLink string) string {
	jsLink = strings.TrimSpace(jsLink)
	if jsLink == "" {
		return ""
	}
	if strings.HasPrefix(jsLink, "http://") || strings.HasPrefix(jsLink, "https://") {
		return jsLink
	}

	baseURL := strings.TrimSpace(homeURL)
	if parsed, err := url.Parse(baseURL); err == nil && parsed != nil && parsed.Scheme != "" && parsed.Host != "" {
		return parsed.Scheme + "://" + parsed.Host + "/" + strings.TrimLeft(jsLink, "/")
	}
	return jsLink
}

func buildTempJSFileName(jsURL string) string {
	sum := sha1.Sum([]byte(jsURL))
	extension := filepath.Ext(strings.TrimSpace(jsURL))
	if extension == "" || len(extension) > 10 {
		extension = ".js"
	}
	return hex.EncodeToString(sum[:]) + extension
}

func buildAssetInfo(found structs.FindSomething) AssetInfo {
	result := AssetInfo{}
	for _, item := range found.Email {
		result.Email = append(result.Email, SensitiveItem{Value: item.Filed, Source: item.Source, AIVerified: item.AIVerified})
	}
	for _, item := range found.IDCard {
		result.IDCard = append(result.IDCard, SensitiveItem{Value: item.Filed, Source: item.Source, AIVerified: item.AIVerified})
	}
	for _, item := range found.Phone {
		result.Phone = append(result.Phone, SensitiveItem{Value: item.Filed, Source: item.Source, AIVerified: item.AIVerified})
	}
	for _, item := range found.IP_URL {
		result.IPURL = append(result.IPURL, SensitiveItem{Value: item.Filed, Source: item.Source, AIVerified: item.AIVerified})
	}
	for _, item := range found.Sensitive {
		result.Sensitive = append(result.Sensitive, SensitiveItem{Value: item.Filed, Source: item.Source, AIVerified: item.AIVerified})
	}
	return result
}

func buildFrontendRoutes(records []crawl.FrontendRouteRecord) []string {
	if len(records) == 0 {
		return nil
	}

	routes := make([]string, 0, len(records))
	for _, record := range records {
		if !isConfirmedFrontendRouteSourceKind(record.SourceKind) {
			continue
		}
		path := normalizeFrontendRoutePath(record.Path)
		if path == "" || !shouldKeepFrontendRoute(path) {
			continue
		}
		routes = append(routes, path)
	}

	return arrayutil.RemoveDuplicates(routes)
}

func isConfirmedFrontendRouteSourceKind(sourceKind string) bool {
	switch strings.TrimSpace(sourceKind) {
	case "router-get-routes",
		"router-options",
		"router-matcher",
		"router-current-matched",
		"router-add-routes",
		"router-add-route",
		"react-router-provider",
		"react-routes-props",
		"react-jsx-routes",
		"router-push",
		"router-replace",
		"history-push",
		"history-replace",
		"hashchange",
		"popstate",
		"guard-target",
		"guard-bypass":
		return true
	default:
		return false
	}
}

func buildStaticAPIRoutes(
	found structs.FindSomething,
	classified crawl.NetworkLinks,
	filter crawl.Filter,
) []string {
	var routes []string
	for _, item := range found.APIRoute {
		if strings.Contains(item.Filed, "[") || strings.Contains(item.Filed, "]") {
			continue
		}
		route := strings.TrimSpace(item.Filed)
		if route != "" {
			routes = append(routes, route)
		}
	}
	for _, route := range classified.Classification.APIRoute {
		trimmedRoute := strings.TrimSpace(route)
		if trimmedRoute != "" {
			routes = append(routes, trimmedRoute)
		}
	}
	return finalizeAPIRoutes(routes, filter)
}

func buildAPIRoutes(
	found structs.FindSomething,
	classified crawl.NetworkLinks,
	apiRecords []crawl.NetworkRecord,
	protocolTraces []crawl.ProtocolTraceRecord,
	filter crawl.Filter,
) []string {
	apiRouter := buildStaticAPIRoutes(found, classified, filter)
	apiRouter = mergeRuntimeAPIRoutes(apiRouter, apiRecords, protocolTraces)
	return finalizeAPIRoutes(apiRouter, filter)
}

func finalizeAPIRoutes(routes []string, filter crawl.Filter) []string {
	routes = preferAbsoluteRuntimeRoutes(routes)
	routes = arrayutil.RemoveDuplicates(routes)
	routes = filter.FilterAPIRoutes(routes)

	sort.Slice(routes, func(i, j int) bool {
		iIsFullURL := strings.HasPrefix(routes[i], "http://") || strings.HasPrefix(routes[i], "https://")
		jIsFullURL := strings.HasPrefix(routes[j], "http://") || strings.HasPrefix(routes[j], "https://")
		if iIsFullURL && !jIsFullURL {
			return true
		}
		if !iIsFullURL && jIsFullURL {
			return false
		}
		return routes[i] < routes[j]
	})

	return routes
}

func buildAPIRoots(targetURL string, apiRouter []string, classified crawl.NetworkLinks, filter crawl.Filter) []string {
	apiRoots := filter.APIRoots(apiRouter, 1)
	allApiRoots := classified.Classification.APIRoot
	for _, item := range classified.Classification.APIRoot {
		for _, v := range apiRoots {
			if !strings.Contains(item, v) {
				allApiRoots = append(allApiRoots, v)
			}
		}
	}
	allApiRoots = append(allApiRoots, apiRoots...)
	allApiRoots = arrayutil.RemoveDuplicates(allApiRoots)

	if parsedURL, err := url.Parse(targetURL); err == nil && parsedURL.Scheme != "" && parsedURL.Host != "" {
		siteRoot := fmt.Sprintf("%s://%s", parsedURL.Scheme, parsedURL.Host)
		allApiRoots = append(allApiRoots, siteRoot)
		allApiRoots = arrayutil.RemoveDuplicates(allApiRoots)
	}

	if len(allApiRoots) == 0 {
		if parsedURL, err := url.Parse(targetURL); err == nil && parsedURL.Scheme != "" && parsedURL.Host != "" {
			allApiRoots = append(allApiRoots, fmt.Sprintf("%s://%s", parsedURL.Scheme, parsedURL.Host))
		}
	}

	return preferAbsoluteAPIRoots(allApiRoots)
}

func buildAssetVulnerabilities(assets AssetInfo) []database.VulnRecord {
	now := time.Now()
	var vulns []database.VulnRecord

	appendVulnerability := func(level, title, vulnType string, items []SensitiveItem) {
		for _, item := range items {
			vulns = append(vulns, database.VulnRecord{
				VulnID:      uuid.New().String(),
				Title:       title,
				Level:       level,
				Type:        vulnType,
				URL:         item.Source,
				Method:      http.MethodGet,
				Description: fmt.Sprintf("发现%s: %s", title, item.Value),
				AIVerified:  item.AIVerified,
				CreatedAt:   now,
			})
		}
	}

	appendVulnerability("low", "身份证号码泄露", "敏感信息泄露", assets.IDCard)
	appendVulnerability("low", "手机号码泄露", "敏感信息泄露", assets.Phone)
	appendVulnerability("medium", "敏感关键词泄露", "敏感信息泄露", assets.Sensitive)

	return vulns
}

func dedupeAssets(assets *AssetInfo) {
	if assets == nil {
		return
	}
	assets.Email = dedupeSensitiveItems(assets.Email)
	assets.IDCard = dedupeSensitiveItems(assets.IDCard)
	assets.Phone = dedupeSensitiveItems(assets.Phone)
	assets.IPURL = dedupeSensitiveItems(assets.IPURL)
	assets.Sensitive = dedupeSensitiveItems(assets.Sensitive)
	assets.FrontendRoutes = arrayutil.RemoveDuplicates(assets.FrontendRoutes)
	assets.APIRoutes = arrayutil.RemoveDuplicates(assets.APIRoutes)
	assets.APIRoots = arrayutil.RemoveDuplicates(assets.APIRoots)
}

func normalizeFrontendRoutePath(raw string) string {
	trimmed := strings.TrimSpace(raw)
	if trimmed == "" {
		return ""
	}
	if trimmed == "*" || trimmed == "/*" {
		return trimmed
	}

	if strings.Contains(trimmed, "/#/") {
		trimmed = trimmed[strings.Index(trimmed, "/#/")+2:]
	}
	if strings.HasPrefix(trimmed, "#") {
		trimmed = strings.TrimPrefix(trimmed, "#")
	}

	parsed, err := url.Parse(trimmed)
	if err == nil {
		switch {
		case parsed.Fragment != "" && strings.HasPrefix(parsed.Fragment, "/"):
			trimmed = parsed.Fragment
		case parsed.Path != "":
			trimmed = parsed.Path
		}
	}

	if idx := strings.Index(trimmed, "#/"); idx >= 0 {
		trimmed = trimmed[idx+1:]
	}
	if idx := strings.IndexAny(trimmed, "?#"); idx >= 0 {
		trimmed = trimmed[:idx]
	}
	if trimmed == "" {
		return ""
	}
	if !strings.HasPrefix(trimmed, "/") {
		trimmed = "/" + trimmed
	}
	trimmed = strings.ReplaceAll(trimmed, "//", "/")
	return strings.TrimSpace(trimmed)
}

func shouldKeepFrontendRoute(route string) bool {
	normalized := strings.ToLower(strings.TrimSpace(route))
	if normalized == "" || normalized == "/" {
		return false
	}
	if strings.HasPrefix(normalized, "/api") {
		return false
	}
	for _, ext := range []string{".js", ".css", ".png", ".jpg", ".jpeg", ".gif", ".svg", ".ico", ".woff", ".woff2", ".ttf", ".map"} {
		if strings.HasSuffix(normalized, ext) {
			return false
		}
	}
	for _, keyword := range []string{"/static/", "/assets/", "/images/", "/img/", "/fonts/"} {
		if strings.Contains(normalized, keyword) {
			return false
		}
	}
	return strings.Count(normalized, "/") <= 12
}

func dedupeSensitiveItems(items []SensitiveItem) []SensitiveItem {
	seen := make(map[string]int, len(items))
	result := make([]SensitiveItem, 0, len(items))
	for _, item := range items {
		key := strings.TrimSpace(item.Value) + "|" + strings.TrimSpace(item.Source)
		if index, ok := seen[key]; ok {
			result[index].AIVerified = result[index].AIVerified || item.AIVerified
			continue
		}
		seen[key] = len(result)
		result = append(result, item)
	}
	return result
}

func annotateUnauthorizedNoise(vulns []database.VulnRecord, reviewer denyTemplateAIReviewer, filteredTemplates map[string]struct{}) []database.VulnRecord {
	if len(vulns) == 0 {
		return vulns
	}

	filtered := make([]database.VulnRecord, 0, len(vulns))
	for index := range vulns {
		vuln := vulns[index]
		if !isUnauthorizedVuln(vuln) {
			filtered = append(filtered, vuln)
			continue
		}

		// Unauthorised findings are only retained after an individual AI review.
		// A missing/failed reviewer is fail-closed so no unchecked result is stored.
		if reviewer == nil {
			continue
		}

		cacheKey := buildUnauthorizedFilterCacheKey(vuln)
		if _, exists := filteredTemplates[cacheKey]; exists {
			continue
		}

		var review crawl.UnauthorizedAIReview
		var err error
		if structuredReviewer, ok := reviewer.(unauthorizedAIReviewer); ok {
			review, err = structuredReviewer.ReviewUnauthorizedAccess(vuln.URL, vuln.Request, vuln.Response)
		} else {
			// Compatibility path for callers that provide the old boolean reviewer.
			var denyTemplate bool
			var reason string
			denyTemplate, reason, err = reviewer.JudgeDenyTemplate(vuln.Request, vuln.Response)
			review = crawl.UnauthorizedAIReview{
				Verdict:           "CONFIRMED",
				VulnerabilityType: "UNKNOWN",
				Confidence:        50,
				Reason:            reason,
				RiskLevel:         "UNKNOWN",
			}
			if denyTemplate {
				review.Verdict = "FALSE_POSITIVE"
				review.VulnerabilityType = "UNKNOWN"
			}
		}
		if err != nil {
			continue
		}
		if review.IsFalsePositive() {
			if cacheKey != "" {
				filteredTemplates[cacheKey] = struct{}{}
			}
			continue
		}

		// AIVerified means the candidate was reviewed by AI. It does not mean
		// the AI confirmed a vulnerability; manual-review results remain visible
		// for SDK consumers that already depend on this flag.
		vuln.AIVerified = review.Verdict == "CONFIRMED" || review.Verdict == "NEEDS_MANUAL_REVIEW"
		vuln.AIReviewVerdict = review.Verdict
		vuln.AIReviewType = review.VulnerabilityType
		vuln.AIReviewConfidence = review.Confidence
		vuln.AIReviewReason = strings.TrimSpace(review.Reason)
		if review.Verdict == "NEEDS_MANUAL_REVIEW" {
			if vuln.AIReviewConfidence > manualUnauthorizedReviewConfidenceCap {
				vuln.AIReviewConfidence = manualUnauthorizedReviewConfidenceCap
			}
			vuln.Confidence = downgradeUnauthorizedConfidence(vuln.Confidence)
			vuln.ConfidenceReason = appendReviewReason(vuln.ConfidenceReason, "AI复核结论: 需人工复核，已降低置信度")
		}
		filtered = append(filtered, vuln)
	}

	return filtered
}

func downgradeUnauthorizedConfidence(level string) string {
	switch strings.ToLower(strings.TrimSpace(level)) {
	case "high":
		return "medium"
	case "medium":
		return "low"
	default:
		return level
	}
}

func appendReviewReason(existing, review string) string {
	existing = strings.TrimSpace(existing)
	review = strings.TrimSpace(review)
	if existing == "" {
		return review
	}
	if review == "" {
		return existing
	}
	return existing + "；" + review
}

var dynamicURIErrorPattern = regexp.MustCompile(`(?i)((?:错误的|无效的|invalid|bad)\s*(?:uri|url)\s*[:：]?\s*)[^"\\]+`)

func buildUnauthorizedFilterCacheKey(vuln database.VulnRecord) string {
	parsed, err := url.Parse(strings.TrimSpace(vuln.URL))
	if err != nil || parsed.Host == "" {
		return ""
	}

	template := normalizeResponseFingerprint(vuln.Response)
	if template == "" {
		return ""
	}
	template = dynamicURIErrorPattern.ReplaceAllString(template, "${1}<route>")
	return strings.ToLower(parsed.Host) + "|" + template
}

func isUnauthorizedVuln(vuln database.VulnRecord) bool {
	return vuln.Type == "未授权访问" || vuln.Title == "未授权访问"
}

func shouldKeepDenyTemplateCluster(cluster *denyTemplateCluster, reviewer denyTemplateAIReviewer) (bool, bool) {
	if cluster == nil || len(cluster.items) == 0 {
		return false, false
	}
	if reviewer == nil {
		return true, false
	}

	cacheKey := cluster.kind + ":" + cluster.fingerprint
	if cached, ok := denyTemplateAIReviewCache.Load(cacheKey); ok {
		if result, ok := cached.(denyTemplateAIReviewResult); ok {
			return result.confirmed, true
		}
	}

	sample := pickDenyTemplateRepresentative(cluster.items)
	if sample == nil {
		return true, false
	}

	confirmed, _, err := reviewer.JudgeDenyTemplate(sample.Request, sample.Response)
	if err != nil {
		return true, false
	}

	denyTemplateAIReviewCache.Store(cacheKey, denyTemplateAIReviewResult{confirmed: confirmed})
	return confirmed, true
}

func pickDenyTemplateRepresentative(items []*database.VulnRecord) *database.VulnRecord {
	if len(items) == 0 {
		return nil
	}

	best := items[0]
	bestScore := denyTemplateRepresentativeScore(best)
	for _, item := range items[1:] {
		score := denyTemplateRepresentativeScore(item)
		if score > bestScore {
			best = item
			bestScore = score
		}
	}
	return best
}

func denyTemplateRepresentativeScore(vuln *database.VulnRecord) int {
	if vuln == nil {
		return -1
	}
	return len(strings.TrimSpace(vuln.Request))*2 + len(strings.TrimSpace(vuln.Response))
}

func buildDenyTemplateFingerprint(vuln database.VulnRecord) (string, string, string, bool) {
	normalizedResponse := strings.TrimSpace(vuln.Response)
	if normalizedResponse == "" {
		return "", "", "", false
	}

	shortResponse := len(normalizedResponse) <= 1024
	normalizedBody := normalizeResponseFingerprint(normalizedResponse)
	if normalizedBody == "" {
		return "", "", "", false
	}

	score := 0
	kind := "deny_template"
	label := "疑似统一拒绝模板"

	if shortResponse {
		score += 2
	}
	if vuln.ResponseLength > 0 && vuln.ResponseLength <= 256 {
		score += 2
	}
	if strings.Contains(normalizedBody, `"success":false`) || strings.Contains(normalizedBody, `"ok":false`) {
		score += 2
	}

	authSignalCount := countAuthSignals(normalizedBody)
	if authSignalCount > 0 {
		score += authSignalCount * 2
		kind = "auth_required"
		label = "疑似统一认证拒绝模板"
	}

	if strings.Contains(normalizedBody, `"data":null`) || strings.Contains(normalizedBody, `"result":null`) {
		score += 1
	}

	if strings.Contains(normalizedBody, `"from":"`) && strings.Contains(normalizedBody, `auth`) {
		score += 2
		kind = "auth_required"
		label = "疑似统一认证拒绝模板"
	}

	if score < 4 {
		return "", "", "", false
	}

	fingerprint := normalizedBody
	if len(fingerprint) > 512 {
		fingerprint = fingerprint[:512]
	}

	return fingerprint, kind, label, true
}

func normalizeResponseFingerprint(response string) string {
	trimmed := strings.TrimSpace(response)
	if trimmed == "" {
		return ""
	}

	var data any
	if err := json.Unmarshal([]byte(trimmed), &data); err == nil {
		return canonicalizeJSONValue(data)
	}

	lower := strings.ToLower(trimmed)
	return strings.Join(strings.Fields(lower), " ")
}

func canonicalizeJSONValue(value any) string {
	switch typed := value.(type) {
	case map[string]any:
		keys := make([]string, 0, len(typed))
		for key := range typed {
			keys = append(keys, key)
		}
		sort.Strings(keys)

		parts := make([]string, 0, len(keys))
		for _, key := range keys {
			normalizedKey := strings.ToLower(key)
			if isVolatileResponseKey(normalizedKey) {
				parts = append(parts, strconv.Quote(normalizedKey)+`:"<volatile>"`)
				continue
			}
			parts = append(parts, strconv.Quote(normalizedKey)+":"+canonicalizeJSONValue(typed[key]))
		}
		return "{" + strings.Join(parts, ",") + "}"
	case []any:
		if len(typed) == 0 {
			return "[]"
		}
		if len(typed) > 3 {
			typed = typed[:3]
		}
		parts := make([]string, 0, len(typed))
		for _, item := range typed {
			parts = append(parts, canonicalizeJSONValue(item))
		}
		return "[" + strings.Join(parts, ",") + "]"
	case string:
		normalized := strings.ToLower(strings.TrimSpace(typed))
		normalized = strings.Join(strings.Fields(normalized), " ")
		return strconv.Quote(normalized)
	case bool:
		if typed {
			return "true"
		}
		return "false"
	case nil:
		return "null"
	case float64:
		return strconv.FormatFloat(typed, 'f', -1, 64)
	default:
		return fmt.Sprintf("%v", typed)
	}
}

func countAuthSignals(body string) int {
	signals := []string{
		"auth", "jwt", "token", "credential", "login", "session", "unauthorized", "forbidden", "permission",
		"凭据", "认证", "鉴权", "登录", "令牌", "未登录", "无权限",
	}

	count := 0
	for _, signal := range signals {
		if strings.Contains(body, signal) {
			count++
		}
	}
	return count
}

func isVolatileResponseKey(key string) bool {
	if _, ok := volatileResponseKeys[key]; ok {
		return true
	}

	return strings.Contains(key, "trace") ||
		strings.Contains(key, "request") ||
		strings.Contains(key, "nonce") ||
		strings.Contains(key, "timestamp") ||
		strings.Contains(key, "error_hint")
}

func shortHash(value string) string {
	sum := sha1.Sum([]byte(value))
	return hex.EncodeToString(sum[:8])
}

func mergeCapturedAPIRecordsWithProtocolTraces(apiRecords []crawl.NetworkRecord, protocolTraces []crawl.ProtocolTraceRecord) []crawl.NetworkRecord {
	merged := make([]crawl.NetworkRecord, 0, len(apiRecords)+len(protocolTraces))
	recordIndex := make(map[string]int, len(apiRecords)+len(protocolTraces))
	traceIndex := make(map[string]int, len(apiRecords)+len(protocolTraces))
	urlMethodIndex := make(map[string]int, len(apiRecords)+len(protocolTraces))

	putRecord := func(record crawl.NetworkRecord) {
		key := strings.TrimSpace(record.Method) + "|" + strings.TrimSpace(record.URL) + "|" + strings.TrimSpace(record.RequestBody)
		urlMethodKey := strings.TrimSpace(record.Method) + "|" + strings.TrimSpace(record.URL)

		idx := -1
		if traceID := strings.TrimSpace(record.TraceID); traceID != "" {
			if existingIdx, ok := traceIndex[traceID]; ok {
				idx = existingIdx
			}
		}
		if idx == -1 {
			if existingIdx, ok := recordIndex[key]; ok {
				idx = existingIdx
			}
		}
		if idx == -1 {
			if existingIdx, ok := urlMethodIndex[urlMethodKey]; ok {
				existing := merged[existingIdx]
				if strings.TrimSpace(existing.RequestBody) == "" || strings.TrimSpace(record.RequestBody) == "" {
					idx = existingIdx
				}
			}
		}

		if idx >= 0 {
			existing := &merged[idx]
			if existing.TraceID == "" {
				existing.TraceID = record.TraceID
			}
			existing.HasProtocolTrace = existing.HasProtocolTrace || record.HasProtocolTrace
			if existing.ResourceType == "" {
				existing.ResourceType = record.ResourceType
			}
			if len(existing.RequestHeaders) == 0 {
				existing.RequestHeaders = record.RequestHeaders
			}
			if existing.RequestBody == "" {
				existing.RequestBody = record.RequestBody
			}
			if len(existing.ResponseHeaders) == 0 {
				existing.ResponseHeaders = record.ResponseHeaders
			}
			if existing.ResponseBody == "" {
				existing.ResponseBody = record.ResponseBody
			}
			if existing.ResponseCode == 0 {
				existing.ResponseCode = record.ResponseCode
			}
			if existing.MIMEType == "" {
				existing.MIMEType = record.MIMEType
			}
			if existing.FetchedAt.IsZero() {
				existing.FetchedAt = record.FetchedAt
			}
			recordIndex[key] = idx
			urlMethodIndex[urlMethodKey] = idx
			if traceID := strings.TrimSpace(existing.TraceID); traceID != "" {
				traceIndex[traceID] = idx
			}
			return
		}

		nextIdx := len(merged)
		recordIndex[key] = nextIdx
		urlMethodIndex[urlMethodKey] = nextIdx
		if traceID := strings.TrimSpace(record.TraceID); traceID != "" {
			traceIndex[traceID] = nextIdx
		}
		merged = append(merged, record)
	}

	for _, record := range apiRecords {
		putRecord(record)
	}

	for _, trace := range protocolTraces {
		requestURL := strings.TrimSpace(trace.RequestURL)
		if requestURL == "" {
			continue
		}

		record := crawl.NetworkRecord{
			URL:              requestURL,
			Method:           trace.Method,
			ResourceType:     trace.Transport,
			TraceID:          trace.TraceID,
			HasProtocolTrace: strings.TrimSpace(trace.TraceID) != "",
			RequestHeaders:   trace.RequestHeaders,
			RequestBody:      trace.FinalRequestBody,
			ResponseBody:     preferTraceResponseBody(trace),
			FetchedAt:        trace.CreatedAt,
		}
		if strings.HasPrefix(strings.TrimSpace(record.ResponseBody), "{") || strings.HasPrefix(strings.TrimSpace(record.ResponseBody), "[") {
			record.MIMEType = "application/json"
		}
		putRecord(record)
	}

	return merged
}

func preferTraceResponseBody(trace crawl.ProtocolTraceRecord) string {
	if body := strings.TrimSpace(trace.SessionMaterials["latest_response_plaintext"]); body != "" {
		return body
	}
	if body := strings.TrimSpace(trace.SessionMaterials["latest_response_ciphertext"]); body != "" {
		return body
	}
	return ""
}

func mergeRuntimeAPIRoutes(routes []string, apiRecords []crawl.NetworkRecord, protocolTraces []crawl.ProtocolTraceRecord) []string {
	merged := append([]string{}, routes...)
	for _, record := range apiRecords {
		if value := strings.TrimSpace(record.URL); value != "" {
			merged = append(merged, value)
		}
	}
	for _, trace := range protocolTraces {
		if value := strings.TrimSpace(trace.RequestURL); value != "" {
			merged = append(merged, value)
		}
	}
	return arrayutil.RemoveDuplicates(merged)
}

type jsHookFrontendRouteDelta struct {
	Path       string
	SourceKind string
	Source     string
	PageURL    string
}

func logJSHookCaptureDelta(
	targetURL string,
	frontendRoutes []string,
	frontendRecords []crawl.FrontendRouteRecord,
	staticAPIRoutes []string,
	finalAPIRoutes []string,
	apiRecords []crawl.NetworkRecord,
	protocolTraces []crawl.ProtocolTraceRecord,
) {
	if !jsHookDebugEnabled() {
		return
	}

	frontendDeltas := buildFrontendRouteDeltas(frontendRoutes, frontendRecords)
	runtimeOnlyAPIRoutes := diffStringSlice(finalAPIRoutes, staticAPIRoutes)

	fmt.Printf(
		"[INFO] JS Hook增量概览 target=%s frontend_routes=%d runtime_api_routes=%d static_api_routes=%d final_api_routes=%d\n",
		targetURL,
		len(frontendDeltas),
		len(runtimeOnlyAPIRoutes),
		len(staticAPIRoutes),
		len(finalAPIRoutes),
	)

	for _, item := range frontendDeltas {
		fmt.Printf(
			"[INFO] JS Hook新增前端路由 target=%s path=%s source_kind=%s source=%s page=%s\n",
			targetURL,
			item.Path,
			item.SourceKind,
			item.Source,
			item.PageURL,
		)
	}

	for _, route := range runtimeOnlyAPIRoutes {
		fmt.Printf(
			"[INFO] JS Hook新增接口路由 target=%s route=%s source=%s\n",
			targetURL,
			route,
			classifyRuntimeAPIRouteSource(route, apiRecords, protocolTraces),
		)
	}
}

func buildFrontendRouteDeltas(routes []string, records []crawl.FrontendRouteRecord) []jsHookFrontendRouteDelta {
	if len(routes) == 0 || len(records) == 0 {
		return nil
	}

	allowed := make(map[string]struct{}, len(routes))
	for _, route := range routes {
		trimmed := strings.TrimSpace(route)
		if trimmed == "" {
			continue
		}
		allowed[trimmed] = struct{}{}
	}

	deltas := make([]jsHookFrontendRouteDelta, 0, len(allowed))
	seen := make(map[string]struct{}, len(allowed))
	for _, record := range records {
		if !isConfirmedFrontendRouteSourceKind(record.SourceKind) {
			continue
		}
		path := normalizeFrontendRoutePath(record.Path)
		if path == "" {
			continue
		}
		if _, ok := allowed[path]; !ok {
			continue
		}
		if _, ok := seen[path]; ok {
			continue
		}
		seen[path] = struct{}{}
		deltas = append(deltas, jsHookFrontendRouteDelta{
			Path:       path,
			SourceKind: strings.TrimSpace(record.SourceKind),
			Source:     strings.TrimSpace(record.Source),
			PageURL:    strings.TrimSpace(record.PageURL),
		})
	}

	sort.Slice(deltas, func(i, j int) bool {
		return deltas[i].Path < deltas[j].Path
	})
	return deltas
}

func diffStringSlice(values []string, baseline []string) []string {
	if len(values) == 0 {
		return nil
	}

	base := make(map[string]struct{}, len(baseline))
	for _, item := range baseline {
		trimmed := strings.TrimSpace(item)
		if trimmed == "" {
			continue
		}
		base[trimmed] = struct{}{}
	}

	var diff []string
	for _, item := range values {
		trimmed := strings.TrimSpace(item)
		if trimmed == "" {
			continue
		}
		if _, ok := base[trimmed]; ok {
			continue
		}
		diff = append(diff, trimmed)
	}
	return arrayutil.RemoveDuplicates(diff)
}

func classifyRuntimeAPIRouteSource(route string, apiRecords []crawl.NetworkRecord, protocolTraces []crawl.ProtocolTraceRecord) string {
	trimmedRoute := strings.TrimSpace(route)
	if trimmedRoute == "" {
		return "unknown"
	}

	recordMatched := false
	for _, trace := range protocolTraces {
		if apiRouteMatchesRuntimeURL(trimmedRoute, trace.RequestURL) {
			return "protocol-trace"
		}
	}
	for _, record := range apiRecords {
		if apiRouteMatchesRuntimeURL(trimmedRoute, record.URL) {
			recordMatched = true
			break
		}
	}
	if recordMatched {
		return "network-record"
	}
	return "runtime"
}

func apiRouteMatchesRuntimeURL(route string, runtimeURL string) bool {
	route = strings.TrimSpace(route)
	runtimeURL = strings.TrimSpace(runtimeURL)
	if route == "" || runtimeURL == "" {
		return false
	}
	if route == runtimeURL {
		return true
	}

	routeParsed, routeErr := url.Parse(route)
	runtimeParsed, runtimeErr := url.Parse(runtimeURL)
	if routeErr == nil && runtimeErr == nil {
		routePath := strings.TrimSpace(routeParsed.Path)
		runtimePath := strings.TrimSpace(runtimeParsed.Path)
		if routePath != "" && routePath == runtimePath {
			return true
		}
	}
	return false
}

func jsHookDebugEnabled() bool {
	raw := strings.TrimSpace(os.Getenv("TRAILBLAZER_DEBUG_JS_HOOK"))
	if raw == "" {
		return false
	}
	enabled, err := strconv.ParseBool(raw)
	if err == nil {
		return enabled
	}
	return raw == "1"
}

func preferAbsoluteRuntimeRoutes(routes []string) []string {
	absoluteByPath := make(map[string]bool)
	for _, route := range routes {
		parsed, err := url.Parse(strings.TrimSpace(route))
		if err != nil || parsed.Scheme == "" || parsed.Host == "" {
			continue
		}
		absoluteByPath[strings.TrimSpace(parsed.Path)] = true
	}

	result := make([]string, 0, len(routes))
	for _, route := range routes {
		trimmed := strings.TrimSpace(route)
		if trimmed == "" {
			continue
		}
		if strings.HasPrefix(trimmed, "/") && absoluteByPath[trimmed] {
			continue
		}
		result = append(result, trimmed)
	}
	return arrayutil.RemoveDuplicates(result)
}

func ensureTrailingSlash(value string) string {
	if strings.HasSuffix(value, "/") {
		return value
	}
	return value + "/"
}

func preferAbsoluteAPIRoots(roots []string) []string {
	absoluteByPath := make(map[string]bool)
	for _, root := range roots {
		parsed, err := url.Parse(strings.TrimSpace(root))
		if err != nil || parsed.Scheme == "" || parsed.Host == "" {
			continue
		}
		absoluteByPath[ensureTrailingSlash(parsed.Path)] = true
	}

	result := make([]string, 0, len(roots))
	for _, root := range roots {
		trimmed := strings.TrimSpace(root)
		if trimmed == "" {
			continue
		}
		if strings.HasPrefix(trimmed, "/") && absoluteByPath[ensureTrailingSlash(trimmed)] {
			continue
		}
		result = append(result, trimmed)
	}
	return arrayutil.RemoveDuplicates(result)
}

func dedupeVulnerabilities(vulns []database.VulnRecord) []database.VulnRecord {
	if len(vulns) <= 1 {
		return vulns
	}

	index := make(map[string]int, len(vulns))
	result := make([]database.VulnRecord, 0, len(vulns))
	for _, vuln := range vulns {
		key := vulnerabilityDedupKey(vuln)
		if idx, ok := index[key]; ok {
			result[idx] = choosePreferredVulnerability(result[idx], vuln)
			continue
		}
		index[key] = len(result)
		result = append(result, vuln)
	}
	return result
}

func vulnerabilityDedupKey(vuln database.VulnRecord) string {
	responseKey := ""
	if isUnauthorizedVuln(vuln) {
		// A trailing slash is commonly accepted as an alias by API gateways. Only
		// merge unauthorized-access findings when the captured response is also
		// identical, so distinct endpoint behaviour is retained.
		responseKey = "|" + strconv.Itoa(vuln.ResponseLength) + "|" + vuln.Response
	}
	parsed, err := url.Parse(strings.TrimSpace(vuln.URL))
	if err == nil && parsed.Host != "" {
		path := parsed.Path
		if isUnauthorizedVuln(vuln) {
			path = strings.TrimSuffix(path, "/")
		}
		return strings.ToUpper(strings.TrimSpace(vuln.Method)) + "|" + strings.ToLower(parsed.Host) + "|" + path + "|" + strings.TrimSpace(vuln.Type) + responseKey
	}
	urlValue := strings.TrimSpace(vuln.URL)
	if isUnauthorizedVuln(vuln) {
		urlValue = strings.TrimSuffix(urlValue, "/")
	}
	return strings.ToUpper(strings.TrimSpace(vuln.Method)) + "|" + urlValue + "|" + strings.TrimSpace(vuln.Type) + responseKey
}

func choosePreferredVulnerability(current, candidate database.VulnRecord) database.VulnRecord {
	if strings.HasPrefix(strings.ToLower(strings.TrimSpace(candidate.URL)), "https://") &&
		!strings.HasPrefix(strings.ToLower(strings.TrimSpace(current.URL)), "https://") {
		return candidate
	}
	if candidate.ResponseLength > current.ResponseLength {
		return candidate
	}
	if len(strings.TrimSpace(candidate.Response)) > len(strings.TrimSpace(current.Response)) {
		return candidate
	}
	return current
}

func bindStaticContexts(vulns []database.VulnRecord, jsResources []database.JSResource) {
	if len(vulns) == 0 || len(jsResources) == 0 {
		return
	}
	for i := range vulns {
		vulns[i].StaticContexts = findStaticContextsForVuln(vulns[i], jsResources)
	}
}

func findStaticContextsForVuln(vuln database.VulnRecord, jsResources []database.JSResource) []database.VulnStaticContext {
	needles := buildStaticContextNeedles(vuln.URL)
	if len(needles) == 0 {
		return nil
	}

	result := make([]database.VulnStaticContext, 0, 3)
	seen := make(map[string]bool)
	for _, resource := range jsResources {
		content := strings.TrimSpace(resource.Content)
		if content == "" {
			continue
		}

		snippet := buildMatchedSnippet(content, needles)
		if snippet == "" {
			continue
		}

		key := strings.TrimSpace(resource.URL) + "|" + snippet
		if seen[key] {
			continue
		}
		seen[key] = true
		result = append(result, database.VulnStaticContext{
			SourceURL: resource.URL,
			Snippet:   snippet,
		})
		if len(result) >= 3 {
			break
		}
	}

	return result
}

func buildStaticContextNeedles(rawURL string) []string {
	normalized := strings.TrimSpace(rawURL)
	if normalized == "" {
		return nil
	}

	needles := make([]string, 0, 4)
	appendNeedle := func(value string) {
		value = strings.TrimSpace(value)
		if value == "" {
			return
		}
		for _, existing := range needles {
			if existing == value {
				return
			}
		}
		needles = append(needles, value)
	}

	appendNeedle(normalized)
	if parsed, err := url.Parse(normalized); err == nil {
		appendNeedle(parsed.Path + parsed.RawQuery)
		if parsed.RawQuery != "" {
			appendNeedle(parsed.Path + "?" + parsed.RawQuery)
		}
		appendNeedle(parsed.Path)
	}

	sort.SliceStable(needles, func(i, j int) bool {
		return len(needles[i]) > len(needles[j])
	})
	return needles
}

func buildMatchedSnippet(content string, needles []string) string {
	if len(needles) == 0 {
		return ""
	}

	lowerContent := strings.ToLower(content)
	for _, needle := range needles {
		lowerNeedle := strings.ToLower(strings.TrimSpace(needle))
		if lowerNeedle == "" {
			continue
		}
		start := strings.Index(lowerContent, lowerNeedle)
		if start < 0 {
			continue
		}
		snippetStart := maxInt(0, start-120)
		snippetEnd := minInt(len(content), start+len(needle)+120)
		prefix := ""
		suffix := ""
		if snippetStart > 0 {
			prefix = "..."
		}
		if snippetEnd < len(content) {
			suffix = "..."
		}
		return prefix + content[snippetStart:snippetEnd] + suffix
	}

	return ""
}

func minInt(left, right int) int {
	if left < right {
		return left
	}
	return right
}

func maxInt(left, right int) int {
	if left > right {
		return left
	}
	return right
}
