name: Backend Build

on:
  workflow_dispatch:

jobs:
  package:
    strategy:
      matrix:
        platform: [windows-latest, macos-14, ubuntu-latest]
        go-version: ['1.24.1']
        arch: [amd64, arm64]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-${{ matrix.arch }}-go-${{ hashFiles('go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.arch }}-go-
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: |
        go mod download
        go mod verify

    - name: Run tests
      run: |
        go test -v ./...

    - name: Build
      shell: bash
      env:
        CGO_ENABLED: 0
        GOOS: ${{ matrix.platform == 'ubuntu-latest' && 'linux' || matrix.platform == 'macos-14' && 'darwin' || 'windows' }}
        GOARCH: ${{ matrix.arch }}
      run: |
        if [ "${{ matrix.platform }}" = "windows-latest" ]; then
          go build -v -ldflags="-s -w" -o trailblazer.exe ./main.go
        else
          go build -v -ldflags="-s -w" -o trailblazer ./main.go
        fi

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trailblazer-${{ matrix.platform }}-${{ matrix.arch }}
        path: ${{ matrix.platform == 'windows-latest' && 'trailblazer.exe' || 'trailblazer' }}
        retention-days: 7

